<?xml version="1.0"  encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:func="http://exslt.org/functions"
                xmlns:bi="http://www.bilendi.com/xslFunctions"
                extension-element-prefixes="func bi"
>

    <!-- Minimal xsl logging mechanism :
       - the global parameter "globalLogLevel" can be either : debug, info, warning, error
         - set this variable to the log level you want from the calling php code via the setParameter method (default is error for production)
       - the "log" template should called with params "level" (so one of these levels) and "message" the message to log.
       - only the messages with level param above ar equal to globalLogLevel variable are generated by this template.
       - with the exception of debug global log level where any message is generated whatever its level.
       FIXME : xsl:message are handled as error of level warning by the php xslt processor, so a workaround is to change
       xsl:message by method calls to a logger object that will log them with the corresponding php/sf error level.
       -->

    <xsl:param name="globalLogLevel" select="'error'"/>
    <func:function name="bi:log">
        <xsl:param name = "level" />
        <xsl:param name = "message" />
        <xsl:choose>
            <xsl:when test="$globalLogLevel='debug'">
                <xsl:message><xsl:value-of select="$message"/></xsl:message>
            </xsl:when>
            <xsl:when test="$globalLogLevel='info'">
                <xsl:if test="contains ('info warning error', $level)">
                    <xsl:message><xsl:value-of select="$message"/></xsl:message>
                </xsl:if>
            </xsl:when>
            <xsl:when test="$globalLogLevel='warning'">
                <xsl:if test="contains ('warning error', $level)">
                    <xsl:message><xsl:value-of select="$message"/></xsl:message>
                </xsl:if>
            </xsl:when>
            <xsl:when test="$globalLogLevel='error'">
                <xsl:if test="contains ('error', $level)">
                    <xsl:message><xsl:value-of select="$message"/></xsl:message>
                </xsl:if>
            </xsl:when>
            <xsl:otherwise>
                <xsl:message><xsl:value-of select="concat('Logging error : the global log level ',$globalLogLevel,' is unknown : nothing logged...')"/></xsl:message>
            </xsl:otherwise>
        </xsl:choose>
        <xsl:message select="$message"/>
    </func:function>
</xsl:stylesheet>